### ISSUE TITLE
Logo Design Offer as Open Source Contribution

### ISSUE THREAD

**Issue by anharismail** [Bphots/HotsWeek#1]
Hello Sir. I'm a UI/UX and Graphics Designer. I'm happy to see an open source project, So, I want provide a logo for you. Would you mind if I propose a new logo design for your project as my Open Source Contribution?

Thanks before.

**Comment by gdlcf88** [comment]
Hi Anhar, thank you so much for the support, the dev team are preparing the release of 3.0 project at 12th July, if the logo fits perfectly, we can consider use it prior to the release. However, we just accepted a new logo approximately half a year ago, and as you know the logo is part of the identity to the app. So we  will probably think twice or even thrice on whether to change the logo again before the 3.0 release. BTW, are you the user of Bphost? And may I please ask how well do you know out project.

**Comment by anharismail** [comment]
Hello @gdlcf88 , in the first I think this project is different from BPHots, then I propose you a logo.

But, if you mean I propose for BPHots main project, I think BPHots have a good logo, so no need to replaced with my logo proposal.

**Comment by gdlcf88** [comment]
@anharismail Hi Anhar,  Thank you so much for reaching out on us, however the core dev team decide we will still stick to the logo we had right now. We greatly appreciate your kind intention, hope we can collab in the future.

**Comment by anharismail** [comment]
No problem, next time maybe I can contribute my design for your project :)
